# Generated by Django 4.2.4 on 2023-08-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="muser",
            options={},
        ),
        migrations.AlterModelManagers(
            name="muser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="muser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="muser",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="muser",
            name="user",
        ),
        migrations.AlterField(
            model_name="muser",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="muser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="muser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="muser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
