# Generated by Django 4.2.4 on 2023-08-23 03:32

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0002_alter_muser_options_alter_muser_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="muser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, unique=True
            ),
        ),
    ]
